DROP TABLE [Phoenix].[MedicaidForms]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Phoenix].[MedicaidForms](
	[FormId] [int] IDENTITY(1,1) NOT NULL,
	[FormName] [nchar](2000) NOT NULL,
 CONSTRAINT [PK_MedicaidForms] PRIMARY KEY CLUSTERED 
(
	[FormId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


