'--Developed by Michael Levine 5/2007--
Public Class ApplicationInformation
    '--FAMIS Application Information Blocks--
    Public BA, BB, BC, BD, BE, BF, BG, BH, BI, BJ, BK, BL, BM, BN, BO, BP, BQ, BR, BS, BT, BU, BV, BW, BX, BY1, BZ As FAMISBlock
    Public CA, CB, CC, CD1, CD2, CE, CF, CG As FAMISBlock
    Public DA1, DA2, DA3, DB, DC, DD1, DD2, DE, DF As FAMISBlock
    Public EA, EB, EC, ED1, ED2, EE, EF, EG, EH, EI, EJ As FAMISBlock
    Public XB, XC, XD, XE, XF, XM, XH, XI, XJ, XK, XL, XN As FAMISBlock

    Public EK, EL, EM, EN, XA, XG As FAMISBlock_Date

    Public Sub New()
        '--Intialize each block individually--
        '--Passing the string representation of the variable allows for easy modular intialization--
        '--All Block format information is found the XML document which is looked at by the FAMISBLock class--
        EK = New FAMISBlock_Date("EK")
        EL = New FAMISBlock_Date("EL")
        EM = New FAMISBlock_Date("EM")
        EN = New FAMISBlock_Date("EN")
        XA = New FAMISBlock_Date("XA")
        XG = New FAMISBlock_Date("XG")

        BA = New FAMISBlock("BA")
        BB = New FAMISBlock("BB")
        BC = New FAMISBlock("BC")
        BD = New FAMISBlock("BD")
        BE = New FAMISBlock("BE")
        BF = New FAMISBlock("BF")
        BG = New FAMISBlock("BG")
        BH = New FAMISBlock("BH")
        BI = New FAMISBlock("BI")
        BJ = New FAMISBlock("BJ")
        BK = New FAMISBlock("BK")
        BL = New FAMISBlock("BL")
        BM = New FAMISBlock("BM")
        BN = New FAMISBlock("BN")
        BO = New FAMISBlock("BO")
        BP = New FAMISBlock("BP")
        BQ = New FAMISBlock("BQ")
        BR = New FAMISBlock("BR")
        BS = New FAMISBlock("BS")
        BT = New FAMISBlock("BT")
        BU = New FAMISBlock("BU")
        BV = New FAMISBlock("BV")
        BW = New FAMISBlock("BW")
        BX = New FAMISBlock("BX")
        BY1 = New FAMISBlock("BY1")
        BZ = New FAMISBlock("BZ")

        CA = New FAMISBlock("CA")
        CB = New FAMISBlock("CB")
        CC = New FAMISBlock("CC")
        CD1 = New FAMISBlock("CD1")
        CD2 = New FAMISBlock("CD2")
        CE = New FAMISBlock("CE")
        CF = New FAMISBlock("CF")
        CG = New FAMISBlock("CG")

        DA1 = New FAMISBlock("DA1")
        da2 = New FAMISBlock("DA2")
        da3 = New FAMISBlock("DA3")
        DB = New FAMISBlock("DB")
        DC = New FAMISBlock("DC")
        DD1 = New FAMISBlock("DD1")
        DD2 = New FAMISBlock("DD2")
        DE = New FAMISBlock("DE")
        DF = New FAMISBlock("DF")

        EA = New FAMISBlock("EA")
        EB = New FAMISBlock("EB")
        EC = New FAMISBlock("EC")
        ED1 = New FAMISBlock("ED1")
        ED2 = New FAMISBlock("ED2")
        EE = New FAMISBlock("EE")
        EF = New FAMISBlock("EF")
        EG = New FAMISBlock("EG")
        EH = New FAMISBlock("EH")
        EI = New FAMISBlock("EI")
        EJ = New FAMISBlock("EJ")

        XB = New FAMISBlock("XB")
        XC = New FAMISBlock("XC")
        XD = New FAMISBlock("XD")
        XE = New FAMISBlock("XE")
        XF = New FAMISBlock("XF")
        XH = New FAMISBlock("XH")
        XI = New FAMISBlock("XI")
        XJ = New FAMISBlock("XJ")
        XK = New FAMISBlock("XK")
        XL = New FAMISBlock("XL")
        XM = New FAMISBlock("XM")
        XN = New FAMISBlock("XN")
    End Sub
    Public Sub Dispose()
        '--Clean up when done--
        EK.Deconstructor()
        EL.Deconstructor()
        EM.Deconstructor()
        EN.Deconstructor()

        BA.Deconstructor()
        BB.Deconstructor()
        BC.Deconstructor()
        BD.Deconstructor()
        BE.Deconstructor()
        BF.Deconstructor()
        BG.Deconstructor()
        BH.Deconstructor()
        BI.Deconstructor()
        BJ.Deconstructor()
        BK.Deconstructor()
        BL.Deconstructor()
        BM.Deconstructor()
        BO.Deconstructor()
        BP.Deconstructor()
        BQ.Deconstructor()
        BR.Deconstructor()
        BS.Deconstructor()
        BT.Deconstructor()
        BU.Deconstructor()
        BV.Deconstructor()
        BW.Deconstructor()
        BX.Deconstructor()
        BY1.Deconstructor()
        BZ.Deconstructor()
        CA.Deconstructor()
        CB.Deconstructor()
        CC.Deconstructor()
        CD1.Deconstructor()
        CD2.Deconstructor()
        CE.Deconstructor()
        CF.Deconstructor()
        CG.Deconstructor()
        DA1.Deconstructor()
        da2.deconstructor()
        da3.deconstructor()
        DB.Deconstructor()
        DC.Deconstructor()
        DD1.Deconstructor()
        DD2.Deconstructor()
        DE.Deconstructor()
        DF.Deconstructor()
        EA.Deconstructor()
        EB.Deconstructor()
        EC.Deconstructor()
        ED1.Deconstructor()
        ED2.Deconstructor()
        EE.Deconstructor()
        EF.Deconstructor()
        EG.Deconstructor()
        EH.Deconstructor()
        EJ.Deconstructor()
    End Sub

End Class
