Public Class CaseChild
    '--FAMIS Case Child (Form B) Information Blocks--
    Public QA, QB, QC, QD, QE, QE2, QF, QH, QI, QI2, QJ, QL, QM, QN, QO As FAMISBlock
    Public RA, RB, RC, RD, RE, RF, RG, RH, RH2, RI, RJ1, RJ2, RK, RL, RM, RP, RQ, RR As FAMISBlock
    Public SA, SB, SC, SD, SE, SF, SG, SH, SI, SJ, SK, SL, SM, SN, SO, SP, SQ, SR, SS, ST As FAMISBlock
    Public TA, TB, TC, TD, TF, TG, TH, TI, TI2, TI3, TJ, TK, TM, TN, TO1, TP, TQ, TR, TS As FAMISBlock
    Public UA, UB, UC, UD, UE, UF, UG, UH, UI, UJ, UK, UL As FAMISBlock
    Public QU, RS, TT As FAMISBlock
    Public YA As FAMISBlock

    Public QG, QK, RN, RO, TE, TL, TU As FAMISBlock_Date
    Public RT As FAMISBlock_Date

    Public Sub New()
        '--Intialize each block individually--
        '--Passing the string representation of the variable allows for easy modular intialization--
        '--All Block format information is found the XML document which is looked at by the FAMISBLock class--
        QA = New FAMISBlock("QA")
        QB = New FAMISBlock("QB")
        QC = New FAMISBlock("QC")
        QD = New FAMISBlock("QD")
        QE = New FAMISBlock("QE")
        QE2 = New FAMISBlock("QE2")
        QF = New FAMISBlock("QF")
        QH = New FAMISBlock("QH")
        QI = New FAMISBlock("QI")
        QI2 = New FAMISBlock("QI2")
        QJ = New FAMISBlock("QJ")
        QL = New FAMISBlock("QL")
        QM = New FAMISBlock("QM")
        QN = New FAMISBlock("QN")
        QO = New FAMISBlock("QO")

        RA = New FAMISBlock("RA")
        RB = New FAMISBlock("RB")
        RC = New FAMISBlock("RC")
        RD = New FAMISBlock("RD")
        RE = New FAMISBlock("RE")
        RF = New FAMISBlock("RF")
        RG = New FAMISBlock("RG")
        RH = New FAMISBlock("RH")
        RH2 = New FAMISBlock("RH2")
        RI = New FAMISBlock("RI")
        RJ1 = New FAMISBlock("RJ1")
        RJ2 = New FAMISBlock("RJ2")
        RK = New FAMISBlock("RK")
        RL = New FAMISBlock("RL")
        RM = New FAMISBlock("RM")
        RP = New FAMISBlock("RP")
        RQ = New FAMISBlock("RQ")
        RR = New FAMISBlock("RR")

        SA = New FAMISBlock("SA")
        SB = New FAMISBlock("SB")
        SC = New FAMISBlock("SC")
        SD = New FAMISBlock("SD")
        SE = New FAMISBlock("SE")
        SF = New FAMISBlock("SF")
        SG = New FAMISBlock("SG")
        SH = New FAMISBlock("SH")
        SI = New FAMISBlock("SI")
        SJ = New FAMISBlock("SJ")
        SK = New FAMISBlock("SK")
        SL = New FAMISBlock("SL")
        SM = New FAMISBlock("SM")
        SN = New FAMISBlock("SN")
        SO = New FAMISBlock("SO")
        SP = New FAMISBlock("SP")
        SQ = New FAMISBlock("SQ")
        SR = New FAMISBlock("SR")
        SS = New FAMISBlock("SS")
        ST = New FAMISBlock("ST")

        TA = New FAMISBlock("TA")
        TB = New FAMISBlock("TB")
        TC = New FAMISBlock("TC")
        TD = New FAMISBlock("TD")
        TF = New FAMISBlock("TF")
        TG = New FAMISBlock("TG")
        TH = New FAMISBlock("TH")
        TI = New FAMISBlock("TI")
        TI2 = New FAMISBlock("TI2")
        TI3 = New FAMISBlock("TI3")
        TJ = New FAMISBlock("TJ")
        TK = New FAMISBlock("TK")
        TM = New FAMISBlock("TM")
        TN = New FAMISBlock("TN")
        TO1 = New FAMISBlock("TO1")
        TP = New FAMISBlock("TP")
        TQ = New FAMISBlock("TQ")
        TR = New FAMISBlock("TR")
        TS = New FAMISBlock("TS")

        UA = New FAMISBlock("UA")
        UB = New FAMISBlock("UB")
        UC = New FAMISBlock("UC")
        UD = New FAMISBlock("UD")
        UE = New FAMISBlock("UE")
        UF = New FAMISBlock("UF")
        UG = New FAMISBlock("UG")
        UH = New FAMISBlock("UH")
        UI = New FAMISBlock("UI")
        UJ = New FAMISBlock("UJ")
        UK = New FAMISBlock("UK")
        UL = New FAMISBlock("UL")

        QU = New FAMISBlock("QU")
        RS = New FAMISBlock("RS")
        TT = New FAMISBlock("TT")
        YA = New FAMISBlock("YA")

        QG = New FAMISBlock_Date("QG")
        QK = New FAMISBlock_Date("QK")
        RN = New FAMISBlock_Date("RN")
        RO = New FAMISBlock_Date("RO")
        TE = New FAMISBlock_Date("TE")
        TL = New FAMISBlock_Date("TL")
        RT = New FAMISBlock_Date("RT")
        TU = New FAMISBlock_Date("TU")
    End Sub
    Public Sub Dispose()
        '--Clean up when done--
        QA.Deconstructor()
        QB.Deconstructor()
        QC.Deconstructor()
        QD.Deconstructor()
        QE.Deconstructor()
        QE2.Deconstructor()
        QF.Deconstructor()
        QH.Deconstructor()
        QI.Deconstructor()
        QI2.Deconstructor()
        QJ.Deconstructor()
        QL.Deconstructor()
        QM.Deconstructor()
        QN.Deconstructor()
        QO.Deconstructor()

        RA.Deconstructor()
        RB.Deconstructor()
        RC.Deconstructor()
        RD.Deconstructor()
        RE.Deconstructor()
        RF.Deconstructor()
        RG.Deconstructor()
        RH.Deconstructor()
        RH2.Deconstructor()
        RI.Deconstructor()
        RJ1.Deconstructor()
        RJ2.Deconstructor()
        RK.Deconstructor()
        RL.Deconstructor()
        RM.Deconstructor()
        RP.Deconstructor()
        RQ.Deconstructor()
        RR.Deconstructor()

        SA.Deconstructor()
        SB.Deconstructor()
        SC.Deconstructor()
        SD.Deconstructor()
        SE.Deconstructor()
        SF.Deconstructor()
        SG.Deconstructor()
        SH.Deconstructor()
        SI.Deconstructor()
        SJ.Deconstructor()
        SK.Deconstructor()
        SL.Deconstructor()
        SM.Deconstructor()
        SN.Deconstructor()
        SO.Deconstructor()
        SP.Deconstructor()
        SQ.Deconstructor()
        SR.Deconstructor()
        SS.Deconstructor()
        ST.Deconstructor()

        TA.Deconstructor()
        TB.Deconstructor()
        TC.Deconstructor()
        TD.Deconstructor()
        TF.Deconstructor()
        TG.Deconstructor()
        TH.Deconstructor()
        TI.Deconstructor()
        TI2.Deconstructor()
        TI3.Deconstructor()
        TJ.Deconstructor()
        TK.Deconstructor()
        TM.Deconstructor()
        TN.Deconstructor()
        TO1.Deconstructor()
        TP.Deconstructor()
        TQ.Deconstructor()
        TR.Deconstructor()
        TS.Deconstructor()

        UA.Deconstructor()
        UB.Deconstructor()
        UC.Deconstructor()
        UD.Deconstructor()
        UE.Deconstructor()
        UF.Deconstructor()
        UG.Deconstructor()
        UH.Deconstructor()
        UI.Deconstructor()
        UJ.Deconstructor()
        UK.Deconstructor()
        UL.Deconstructor()

        QU.Deconstructor()
        RS.Deconstructor()
        TT.Deconstructor()
        YA.Deconstructor()

        QG.Deconstructor()
        QK.Deconstructor()
        RN.Deconstructor()
        RO.Deconstructor()
        TE.Deconstructor()
        TL.Deconstructor()
        RT.Deconstructor()
    End Sub
End Class
