'--Developed by Michael Levine 5/2007--
Public Class FoodStampInformation
    '--FAMIS Food Stamp Information Blocks--
    Public LA, LB, LF, LG, LH, LI, LJ, LK, LL, LM, LN, LO, LP, LQ, LR, LS As FAMISBlock
    Public MA, MB, MC, MD, ME1, MF, MG, MH, MI, MJ, MK, ML, MM, MN, MO, MP, MQ, MR, MS, MT As FAMISBlock
    Public NA, NB, NC, ND, NE, NF, NH, NI, NJ, NK, NL, NM, NN, NO, NP As FAMISBlock
    Public OA, OB, OC, OD, OE, OF1, OG, OH, OI, OJ, OK, OK1, OL, OM, ON1, OO, OP As FAMISBlock
    Public MU, NQ, NR, NS, NU, NV, NW, [OR], VB, VF, VH, OQ1, OQ2 As FAMISBlock
    Public WX, WY As FAMISBlock

    Public LC, LD, LE, LT, NG, NT As FAMISBlock_Date

    Public Sub New()
        '--Intialize each block individually--
        '--Passing the string representation of the variable allows for easy modular intialization--
        '--All Block format information is found the XML document which is looked at by the FAMISBLock class--
        LA = New FAMISBlock("LA")
        LB = New FAMISBlock("LB")
        LF = New FAMISBlock("LF")
        LG = New FAMISBlock("LG")
        LH = New FAMISBlock("LH")
        LI = New FAMISBlock("LI")
        LJ = New FAMISBlock("LJ")
        LK = New FAMISBlock("LK")
        LL = New FAMISBlock("LL")
        LM = New FAMISBlock("LM")
        LN = New FAMISBlock("LN")
        LO = New FAMISBlock("LO")
        LP = New FAMISBlock("LP")
        LQ = New FAMISBlock("LQ")
        LR = New FAMISBlock("LR")
        LS = New FAMISBlock("LS")

        MA = New FAMISBlock("MA")
        MB = New FAMISBlock("MB")
        MC = New FAMISBlock("MC")
        MD = New FAMISBlock("MD")
        ME1 = New FAMISBlock("ME1")
        MF = New FAMISBlock("MF")
        MG = New FAMISBlock("MG")
        MH = New FAMISBlock("MH")
        MI = New FAMISBlock("MI")
        MJ = New FAMISBlock("MJ")
        MK = New FAMISBlock("MK")
        ML = New FAMISBlock("ML")
        MM = New FAMISBlock("MM")
        MN = New FAMISBlock("MN")
        MO = New FAMISBlock("MO")
        MP = New FAMISBlock("MP")
        MQ = New FAMISBlock("MQ")
        MR = New FAMISBlock("MR")
        MS = New FAMISBlock("MS")
        MT = New FAMISBlock("MT")
        OQ1 = New FAMISBlock("OQ1")
        OQ2 = New FAMISBlock("OQ2")

        NA = New FAMISBlock("NA")
        NB = New FAMISBlock("NB")
        NC = New FAMISBlock("NC")
        ND = New FAMISBlock("ND")
        NE = New FAMISBlock("NE")
        NF = New FAMISBlock("NF")
        NH = New FAMISBlock("NH")
        NI = New FAMISBlock("NI")
        NJ = New FAMISBlock("NJ")
        NK = New FAMISBlock("NK")
        NL = New FAMISBlock("NL")
        NM = New FAMISBlock("NM")
        NN = New FAMISBlock("NN")
        NO = New FAMISBlock("NO")
        NP = New FAMISBlock("NP")

        OA = New FAMISBlock("OA")
        OB = New FAMISBlock("OB")
        OC = New FAMISBlock("OC")
        OD = New FAMISBlock("OD")
        OE = New FAMISBlock("OE")
        OF1 = New FAMISBlock("OF1")
        OG = New FAMISBlock("OG")
        OH = New FAMISBlock("OH")
        OI = New FAMISBlock("OI")
        OJ = New FAMISBlock("OJ")
        OK = New FAMISBlock("OK")
        OK1 = New FAMISBlock("OK1")
        OL = New FAMISBlock("OL")
        OM = New FAMISBlock("OM")
        ON1 = New FAMISBlock("ON1")
        OO = New FAMISBlock("OO")
        OP = New FAMISBlock("OP")

        WX = New FAMISBlock("WX")
        WY = New FAMISBlock("WY")

        MU = New FAMISBlock("MU")
        NQ = New FAMISBlock("NQ")
        NR = New FAMISBlock("NR")
        NS = New FAMISBlock("NS")
        NU = New FAMISBlock("NU")
        NV = New FAMISBlock("NV")
        NW = New FAMISBlock("NW")
        [OR] = New FAMISBlock("OR")
        VB = New FAMISBlock("VB")
        VF = New FAMISBlock("VF")
        VH = New FAMISBlock("VH")

        LC = New FAMISBlock_Date("LC")
        LD = New FAMISBlock_Date("LD")
        LE = New FAMISBlock_Date("LE")
        LT = New FAMISBlock_Date("LT")
        NG = New FAMISBlock_Date("NG")
        NT = New FAMISBlock_Date("NT")
    End Sub
    Public Sub Dispose()
        '--Clean up when done--
        LA.Deconstructor()
        LB.Deconstructor()
        LF.Deconstructor()
        LG.Deconstructor()
        LH.Deconstructor()
        LI.Deconstructor()
        LJ.Deconstructor()
        LK.Deconstructor()
        LL.Deconstructor()
        LM.Deconstructor()
        LN.Deconstructor()
        LO.Deconstructor()
        LP.Deconstructor()
        LQ.Deconstructor()
        LR.Deconstructor()
        LS.Deconstructor()

        MA.Deconstructor()
        MB.Deconstructor()
        MC.Deconstructor()
        MD.Deconstructor()
        ME1.Deconstructor()
        MF.Deconstructor()
        MG.Deconstructor()
        MH.Deconstructor()
        MI.Deconstructor()
        MJ.Deconstructor()
        MK.Deconstructor()
        ML.Deconstructor()
        MM.Deconstructor()
        MO.Deconstructor()
        MP.Deconstructor()
        MQ.Deconstructor()
        MR.Deconstructor()
        MS.Deconstructor()
        MT.Deconstructor()

        NA.Deconstructor()
        NB.Deconstructor()
        NC.Deconstructor()
        ND.Deconstructor()
        NE.Deconstructor()
        NF.Deconstructor()
        NH.Deconstructor()
        NI.Deconstructor()
        NJ.Deconstructor()
        NK.Deconstructor()
        NL.Deconstructor()
        NM.Deconstructor()
        NN.Deconstructor()
        NO.Deconstructor()
        NP.Deconstructor()

        OA.Deconstructor()
        OB.Deconstructor()
        OC.Deconstructor()
        OD.Deconstructor()
        OE.Deconstructor()
        OF1.Deconstructor()
        OG.Deconstructor()
        OH.Deconstructor()
        OI.Deconstructor()
        OJ.Deconstructor()
        OK.Deconstructor()
        OK1.Deconstructor()
        OL.Deconstructor()
        OM.Deconstructor()
        ON1.Deconstructor()
        OO.Deconstructor()
        OP.Deconstructor()

        WX.Deconstructor()
        WY.Deconstructor()

        MU.Deconstructor()
        NQ.Deconstructor()
        NR.Deconstructor()
        NS.Deconstructor()
        NT.Deconstructor()
        NU.Deconstructor()
        NV.Deconstructor()
        NW.Deconstructor()
        [OR].Deconstructor()
        VB.Deconstructor()
        VF.Deconstructor()
        VH.Deconstructor()
        OQ1.Deconstructor()
        OQ2.Deconstructor()

        LC.Deconstructor()
        LD.Deconstructor()
        LE.Deconstructor()
        LT.Deconstructor()
        NG.Deconstructor()
        NT.Deconstructor()
    End Sub
End Class
