'--Developed by Michael Levine 5/2007--
Public Class IncomeInformation
    '--FAMIS Income Information Blocks--
    Public JA, JB, JC, JD, JE, JF, JG, JH, JI, JJ, JK, JL, JM, JN, JO, JP, JQ, JR, JS, JT, JU, JV, JW, JX As FAMISBlock
    Public KA, KB, KC, KD, KE, KF, KG, KH, KI, KJ, KK, KL, KM, KN, KO, KP, KQ, KR, KS, KT, KU, KV As FAMISBlock


    Public Sub New()
        '--Intialize each block individually--
        '--Passing the string representation of the variable allows for easy modular intialization--
        '--All Block format information is found the XML document which is looked at by the FAMISBLock class--
        JA = New FAMISBlock("JA")
        JB = New FAMISBlock("JB")
        JC = New FAMISBlock("JC")
        JD = New FAMISBlock("JD")
        JE = New FAMISBlock("JE")
        JF = New FAMISBlock("JF")
        JG = New FAMISBlock("JG")
        JH = New FAMISBlock("JH")
        JI = New FAMISBlock("JI")
        JJ = New FAMISBlock("JJ")
        JK = New FAMISBlock("JK")
        JL = New FAMISBlock("JL")
        JM = New FAMISBlock("JM")
        JN = New FAMISBlock("JN")
        JO = New FAMISBlock("JO")
        JP = New FAMISBlock("JP")
        JQ = New FAMISBlock("JQ")
        JR = New FAMISBlock("JR")
        JS = New FAMISBlock("JS")
        JT = New FAMISBlock("JT")
        JU = New FAMISBlock("JU")
        JV = New FAMISBlock("JV")
        JW = New FAMISBlock("JW")
        JX = New FAMISBlock("JX")

        KA = New FAMISBlock("KA")
        KB = New FAMISBlock("KB")
        KC = New FAMISBlock("KC")
        KD = New FAMISBlock("KD")
        KE = New FAMISBlock("KE")
        KF = New FAMISBlock("KF")
        KG = New FAMISBlock("KG")
        KH = New FAMISBlock("KH")
        KI = New FAMISBlock("KI")
        KJ = New FAMISBlock("KJ")
        KK = New FAMISBlock("KK")
        KL = New FAMISBlock("KL")
        KM = New FAMISBlock("KM")
        KN = New FAMISBlock("KN")
        KO = New FAMISBlock("KO")
        KP = New FAMISBlock("KP")
        KQ = New FAMISBlock("KQ")
        KR = New FAMISBlock("KR")
        KS = New FAMISBlock("KS")
        KT = New FAMISBlock("KT")
        KU = New FAMISBlock("KU")
        KV = New FAMISBlock("KV")
    End Sub
    Public Sub Dispose()
        '--Clean up when done--
        JA.Deconstructor()
        JB.Deconstructor()
        JC.Deconstructor()
        JD.Deconstructor()
        JE.Deconstructor()
        JF.Deconstructor()
        JG.Deconstructor()
        JH.Deconstructor()
        JI.Deconstructor()
        JJ.Deconstructor()
        JK.Deconstructor()
        JL.Deconstructor()
        JM.Deconstructor()
        JN.Deconstructor()
        JO.Deconstructor()
        JP.Deconstructor()
        JR.Deconstructor()
        JS.Deconstructor()
        JT.Deconstructor()
        JU.Deconstructor()
        JV.Deconstructor()
        JW.Deconstructor()
        JX.Deconstructor()
        KA.Deconstructor()
        KB.Deconstructor()
        KC.Deconstructor()
        KD.Deconstructor()
        KE.Deconstructor()
        KF.Deconstructor()
        KG.Deconstructor()
        KH.Deconstructor()
        KI.Deconstructor()
        KJ.Deconstructor()
        KK.Deconstructor()
        KL.Deconstructor()
        KM.Deconstructor()
        KN.Deconstructor()
        KO.Deconstructor()
        KP.Deconstructor()
        KQ.Deconstructor()
        KR.Deconstructor()
        KS.Deconstructor()
        KT.Deconstructor()
        KU.Deconstructor()
        KV.Deconstructor()
    End Sub

End Class
